(include "#.scm")

(test-eqv 6 (six.x*y 2 3))
(test-eqv 2 (six.x/y 6 3))
(test-eqv 3 (six.x%y 7 4))
(test-eqv 3 (six.x//y 7 2))
(test-eqv 3 (six.x+y 1 2))
(test-eqv 2 (six.x-y 5 3))
(test-eq #t (six.x==y 1 1))
(test-eq #t (six.x!=y 1 2))
(test-eq #t (six.x<y 1 2))
(test-eq #t (six.x>y 2 1))
(test-eq #t (six.x<=y 1 1))
(test-eq #t (six.x>=y 2 1))
(test-eqv 2 (six.x&&y 1 2))
(test-eqv 1 (six.x&y 3 1))
(test-eqv 2 (six.x^y 3 1))
(test-eqv 8 (six.x<<y 1 3))
(test-eqv 2 (six.x>>y 8 2))
(test-eqv 2 (six.x>>>y 8 2))
(test-eqv 8 (six.x**y 2 3))
(test-eqv 3 (six.+x 3))
(test-eqv -3 (six.-x 3))
(test-eq #f (six.!x 0))
(test-eq #t (six.notx #f))
(test-eqv -1 (six.~x 0))
(test-eq #t (six.x===y 1 1))
(test-eq #t (six.x!==y 1 2))
(test-eqv 1 (six.x?y:z #t 1 2))
(test-eqv 3 (|six.x\|y| 1 2))
(test-eqv 0 (|six.x\|\|y| 0 2))
(test-equal '(1 . 2) (six.cons 1 2))
(test-equal '() (six.null))
(test-equal '(1 . 2) (six.list 1 2))
(test-equal '#(2 2 2) (six.make-array 2 3))
